#pragma config(Motor,  port3,           leftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftA,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool stop = false;
task main()
{
	while (true){

	while

	if(vexRT[Btn7D]==1){//foreward for tony
    	motor[leftA]=-70;//70 for tony
    	motor[leftB]=-70;
    	//wait1Msec(500);
 }
  else if(vexRT[Btn8D]==1){//foreward for james
    	motor[leftA]=60;
    	motor[leftB]=60;
    	//wait1Msec(500);
    }
  else{
  		motor[leftA]=-30;
    	motor[leftB]=-30; //negative for tony
    	//wait1Msec(500);
    }
}
}
