#pragma config(Motor,  port4,           leftA,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftB,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){

	if(vexRT[Btn7D]==1){
    	motor[leftA]=-50;
    	motor[leftB]=-50;
    	//wait1Msec(500);
 }
  else if(vexRT[Btn8D]==1){
    	motor[leftA]=60;
    	motor[leftB]=60;
    	//wait1Msec(500);
    }
  else{
  		motor[leftA]=-10;
    	motor[leftB]=-10;
    	//wait1Msec(500);
    }
}
}
