#pragma config(Sensor, dgtl1,  leftcoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightcoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           clawL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftbase,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightbase,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           clawR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLT,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armLB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRT,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armRB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftR,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SmartMotorLib.c"
  int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
  											// Also helps to prevent from accidental tilting of the analog sticks on the VEX controller, this is VERY important.

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  SmartMotorsInit();

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{


	SmartMotorPtcMonitorEnable();
	SmartMotorRun();

  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.


    /////***** DRIVE CODE *****\\\\\
    // Code to move Forward or Backward

		//#Debug Mode/Getting Variables from X and Y


    //Variables for X
    if (abs(vexRT[Ch1]) > threshold)
    {
    	joy_x = vexRT[Ch1];
    }
    else
    {
    	joy_x = 0;
    }

    //Variables for Y
    if (abs(vexRT[Ch3]) > threshold)
    {
    	joy_y = vexRT[Ch3];
    }
    else
    {
    	joy_y = 0;
    }

    //Drive Code - Super Simple???

    SetMotor(leftbase,(joy_y + joy_x));
    /*SetMotor(leftback,(joy_y + joy_x));*/

		SetMotor(rightbase,(joy_y - joy_x));
    /*SetMotor(rightback,(joy_y - joy_x));*/

 		/////***** ARM CODE *****\\\\\

    if(vexRT[Btn8U]==1)
    {
    	motor[armLT]=-127;
    	motor[armLB]=-127;
    	motor[armRT]=127;
    	motor[armRB]=127;
    }

    else if(vexRT[Btn8D]==1)
    {
    	motor[armLT]=127;
    	motor[armLB]=127;
    	motor[armRB]=-127;
    	motor[armRT]=-127;
    }

    else
    {
    	motor[armLT]=0;
    	motor[armLB]=0;
    	motor[armRT]=0;
    	motor[armRB]=0;
    }

    /////***** LIFT CODE *****\\\\\

    if(vexRT[Btn7U]==1)
    {
    	motor[liftL]=-127;
    	motor[liftR]=127;

    }

    else if(vexRT[Btn8D]==1)
    {
    	motor[liftL]=127;
    	motor[liftR]=-127;
    }

    else
    {
    	motor[liftL]=0;
    	motor[liftR]=0;

    }



  }
}
