#pragma config(Sensor, dgtl1,  Left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Right,          sensorQuadEncoder)
#pragma config(Motor,  port2,           LeftSideBase,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightSideBase, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           Hs1,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           Hs2,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Hs3,           tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Team C Bot Code, Created September 16/2016
task main()
{
motor LeftSideBase = vexRt [Ch3];
motor RightSideBase= vexRT [Ch3];
	//Joystick control for driver
	motor[RightSideBase] =
	motor[LeftSideBase] = chnl1;
}
