#pragma config(Sensor, dgtl1,  leftcoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightcoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           leftfront,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftback,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightback,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightfront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armLTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armL2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armR3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRTop,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           armR2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          armL3,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SmartMotorLib.c"
  int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)\
  											// Also helps to prevent from accidental tilting of the analog sticks on the VEX controller, this is VERY important.

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  SmartMotorsInit();

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	SmartMotorLinkMotors(leftback,leftfront);
	SmartMotorLinkMotors(rightback,rightfront);
	SmartMotorLinkMotors(rightback,leftback);
	SmartMotorPtcMonitorEnable();
	SmartMotorRun();

  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.


    /////***** DRIVE CODE *****\\\\\

    // Code to move Forward or Backward

		//#Debug Mode/Getting Variables from X and Y


    //Variables for X
    if (abs(vexRT[Ch1]) > threshold)
    {
    	joy_x = vexRT[Ch1];
    }
    else
    {
    	joy_x = 0;
    }

    //Variables for Y
    if (abs(vexRT[Ch3]) > threshold)
    {
    	joy_y = vexRT[Ch3];
    }
    else
    {
    	joy_y = 0;
    }

    //Drive Code - Super Simple???

    SetMotor(leftfront,(joy_y + joy_x));
    SetMotor(leftback,(joy_y + joy_x));

		SetMotor(rightfront,(joy_y - joy_x));
    SetMotor(rightback,(joy_y - joy_x));

 		/////***** ARM CODE *****\\\\\


    if(vexRT[Btn7D]==1){
    	motor[armLTop]=-127;
    	motor[armL3]=-127;
    	motor[armRTop]=-127;
    	motor[armR3]=-127;
    }
    else if(vexRT[Btn8D]==1){
    	motor[armLTop]=127;
    	motor[armL2]=-127;
    	motor[armL3]=127;
    	motor[armRTop]=127;
    	motor[armR2]=-127;
    	motor[armR3]=127;
    }
    else{
    	motor[armLTop]=0;
    	motor[armL2]=0;
    	motor[armL3]=0;
    	motor[armRTop]=0;
    	motor[armR2]=0;
    	motor[armR3]=0;
    }

		/////***** FORK LAUNCHER CODE *****\\\\\

		if(vexRT[Btn6U] == 1)           // If button 6U (upper right shoulder button) is pressed:
		{
			SensorValue[solenoid] = 1;  // ?activate the solenoid to put the lift down
		}
		else // If button 6U (upper right shoulder button) is  NOT pressed:
		{
			SensorValue[solenoid] = 0;  // Deactivate solenoid to raise the lift
		}



  }
}
