#pragma config(Sensor, dgtl1,  leftcoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightcoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           leftfront,     tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftback,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightback,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightfront,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armLTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           newmotor1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armR3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           newmotor2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          armL3,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "SmartMotorLib.c"
  int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  SmartMotorsInit();

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	SmartMotorLinkMotors(leftback,leftfront);
	SmartMotorLinkMotors(rightback,rightfront);
	SmartMotorLinkMotors(rightback,leftback);
	SmartMotorPtcMonitorEnable();
	SmartMotorRun();

  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.


    joy_x = vexRT[Ch1];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
    joy_y = vexRT[Ch3];   // This is the LEFT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

    // Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
    if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
    {
      SetMotor(leftfront,((joy_y + joy_x)/2));
      SetMotor(leftback,((joy_y + joy_x)/2));
      SetMotor(rightfront,((joy_y - joy_x)/2));
    	SetMotor(rightback,((joy_y - joy_x)/2));
    }
    // Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
    else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
    {
      SetMotor(leftfront,((joy_y - joy_x)/2));
      SetMotor(leftback,((joy_y - joy_x)/2));
      SetMotor(rightback, ((joy_y + joy_x)/2));
      SetMotor(rightfront, ((joy_y + joy_x)/2));
    }
    // Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
    else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
    {
      SetMotor(leftfront,joy_x);
      SetMotor(leftback,joy_x);
      SetMotor(rightfront,(-1 * joy_x));
    	SetMotor(rightback,(-1 * joy_x));
    }
    // Standing still: (both abs(X) and abs(Y) are below the threshold)
    else
    {
      SetMotor(leftfront,0);
      SetMotor(leftback,0);
      SetMotor(rightfront,0);
      SetMotor(rightback,0);
    }

// former tank drive
    //SetMotor(leftfront,vexRT[Ch3]);
    //setMotor(leftback,vexRT[Ch3]);
    //setMotor(rightback, vexRT[Ch3]);
    //setMotor(rightfront,vexRT[Ch3]);

		/*
		motor[newmotor1]=127;
		motor[newmotor2]=127;
		*/
    if(vexRT[Btn7D]==1){
    	motor[armLTop]=-127;
    	motor[armL3]=-127;
    	motor[armRTop]=-127;
    	motor[armR3]=-127;
    }
    else if(vexRT[Btn8D]==1){
    	motor[armLTop]=127;
    	motor[armL3]=127;
    	motor[armRTop]=127;
    	motor[armR3]=127;
    }
    else{
    	motor[armLTop]=0;
    	motor[armL3]=0;
    	motor[armRTop]=0;
    	motor[armR3]=0;
    }



		if(vexRT[Btn6U] == 1)           // If button 6U (upper right shoulder button) is pressed:
		{
			SensorValue[solenoid] = 1;  // ?activate the solenoid to put the lift down
		}
		else // If button 6U (upper right shoulder button) is  NOT pressed:
		{
			SensorValue[solenoid] = 0;  // Deactivate solenoid to raise the lift
		}



  }
}
